### ISSUE TITLE
how to query DEG for a single cell-cluster across treatment/genotype

### ISSUE THREAD

**Issue by BartBryant** [10XGenomics/loupeR#10]
hello
awesome tool for converting Seurat_Objects into a .cloupe file, will come in handy for collaborations 

i used the 'create_loupe_from_seurat( )' function and got the .cloupe file 

<img width="1512" alt="Screenshot 2023-10-09 at 2 26 48 PM" src="https://github.com/10XGenomics/loupeR/assets/135715545/28d854fd-67e2-4a02-9508-079e6319a73a">
<img width="1512" alt="Screenshot 2023-10-09 at 2 27 05 PM" src="https://github.com/10XGenomics/loupeR/assets/135715545/74488221-3386-4013-9940-18ccc89fc426">

i can run the DEG within loupe browser to query between 2 clusters, but can not compare a single cell cluster across treatment groups (in my case CTRL and treatment). 
i know that I can do DEG on a cell-cluster in Seurat, but was wondering if loupe browser had this capability
thx
Bryant

**Comment by esiegel** [comment]
Seems like you might be hoping to do DiffExp across multiple samples?  I think the support team might be best to help you figure out using Loupe.

You should reach out to support@10xgenomics.com . They are the ones best suited to help with this.
