### ISSUE TITLE
To get row and col information from .loupe file

### ISSUE THREAD

**Issue by hhh-123** [10XGenomics/loupeR#11]
Hello,Thanks for providing us such a wonderful tool!
I have difficult in getting the tissue's 'row' and 'col' information from .loupe file.
From .loupe file, we can only download the 'imagerow' and 'imagecol' information.
I wonder if there is someway to get 'row' and 'col' information from .loupe file or how could transfer 'imagerow' and 'imagecol' to 'row' and 'col'.
Thanks! Best wishes!

**Comment by esiegel** [comment]
I'm not sure I'm understanding your problem.  Are you saying that you have a spatial Loupe file and you are trying to extract extra information from the image?  Maybe you are asking how to get the coordinates of the tissue spots?  Or maybe you are asking how to get the underlying count matrix rows and columns?

For now the LoupeR tool does not support extracting data from a Loupe file, but I'd love to understand your problem.  Maybe you can share screenshots?

**Comment by esiegel** [comment]
Closing this issue as it has been several weeks without a response.
