### ISSUE TITLE
Ensembl link failed

### ISSUE THREAD

**Issue by phoebee-h** [10XGenomics/loupeR#12]
Hi 10x team,

Thank you for developing this package.
When we `read10x()` and then create the seurat object at first, the `gene.colum=2` indicated that only the gene symbol (second column) in the "features.tsv.gz" will be used and stored in seurat object.
This led to the Ensembl link to nothing after generating the .cloupe by loupeR. Do you have any suggestions to fix this issue?

```
dtx <- Read10X(
  data.dir,
  gene.column = 2,
  cell.column = 1,
  unique.features = TRUE,
  strip.suffix = FALSE
)
```

![image](https://github.com/10XGenomics/loupeR/assets/28743573/16497982-c6d4-4c28-a17b-db96556fe679)

Thank you.
Phoebe

**Comment by esiegel** [comment]
Yes, this is a problem that we ran into.  The `Seurat` methods like `read10x` only read in either the names or ensemble ids, but not both.  `loupeR` hardcodes the feature_ids [here](https://github.com/10XGenomics/loupeR/blob/701e11fe48bbf761a5dbf6b4579bd021b67f550f/R/hdf5.R#L63).  `Seurat` takes these feature names and sets them as the rownames on the count matrix.  An R matrix can't have multiple rownames.

I guess one possible solution would be to add a new optional parameter to both `create_loupe_from_seurat` and `create_loupe` that accepts a list of `feature_ids`.

Will give this some thought.

**Comment by esiegel** [comment]
Now you can use:

```R
# A character vector of ensemble ids.
feature_ids <- read_feature_ids_from_tsv("PATH_TO_10X_DATA/features.tsv.gz")

create_loupe_from_seurat(seurat_obj, feature_ids = feature_ids)
```

to include the ensemble ids.  If you filter out features from your seurat object, you will have to do the same with the feature_ids.

**Comment by phoebee-h** [comment]
@esiegel 
Thank you. It works now. 
Besides the filtered-out features you mentioned above, the user should also be aware of the duplicated gene symbol.
