### ISSUE TITLE
Features not showing up as gene names

### ISSUE THREAD

**Issue by Sun-storm** [10XGenomics/loupeR#19]
Hi!

I've been trying to use Loupe and it seems like a very nice tool so far. One of the problems I'm having though is that when I convert my Seurat Umap to the Loupe format and try to visualize the features, they appear as the regions of the genome and not with their names. 

If I visualize those same genes in R with FeaturePlot() I can input the gene names and I get a results, so the information should be within the data I give Loupe. How can I fix this? Here is an example of he options for features I get within Loupe Browser 7:

Chr2-10023-10889
Gene
Feature_4934

Thank you for the help!

**Comment by esiegel** [comment]
Is the issue that the Ensemble Ids are not included in the Loupe file?  Sadly, a seurat object will only include either the gene names or the ensemble ids.  In order to include the ensemble ids see this example, which is also included in the README.

```R
# import the library
library("loupeR")

# Gene Expression RNA assay
assay <- seurat_obj[["RNA"]]

# A character vector of ensemble ids.
feature_ids <- read_feature_ids_from_tsv("PATH_TO_10X_DATA/features.tsv.gz")

create_loupe_from_seurat(seurat_obj, feature_ids = feature_ids)
```

**Comment by Sun-storm** [comment]
Hi Esiegel,

thank you for your answer. I'm afraid I can't find a features.tsv.gz document (or a features documents at all).

These are the documents I have. Am I looking in the wrong place?

<img width="221" alt="image" src="https://github.com/10XGenomics/loupeR/assets/93934490/97f61215-bfc6-433a-9f64-db9048607af5">

**Comment by esiegel** [comment]
Currently, this tool only support gene expression data, or the `RNA` dataset in seurat.

Usually the tsv file can be found in the `filtered_feature_bc_matrix` directory.   Not familiar with all datasets.  Maybe scATAC doesn't store it there

**Comment by esiegel** [comment]
Closing the ticket as the solution is find the ensemble ids that should be with the cellranger outs.  At least that is the case with Gene expression datasets.
