### ISSUE TITLE
Error in select_assay(obj) : no slot of name "counts" for this object of class "Assay5"

### ISSUE THREAD

**Issue by sonalhenson** [10XGenomics/loupeR#21]
Hello,

Firstly, thank you for creating this package. It is exactly what I am looking for if I can get it to work. 

I get the error below upon calling the create_loupe_from_seurat method:
```
Error in select_assay(obj) : 
  no slot of name "counts" for this object of class "Assay5"
```
My matrix is not generated by cellranger but by epi2me-labs/wf-single-cell workflow using nanopore data, so I've only used the counts matrix as input for the Seurat object. Irrespective of this, even when I try calling create_loupe_from_seurat using 10X data, like in the demo tutorial you link to in the README, I get the same error. This makes me wonder if there is something peculiar about my loupeR or Seurat installation. I'd appreciate any help to resolve this.

I'm running (if this helps):
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS
other attached packages:
[1] hdf5r_1.3.8        loupeR_1.0.1       dplyr_1.1.4        cowplot_1.1.1      ggplot2_3.4.4      Seurat_5.0.1       SeuratObject_5.0.1
[8] sp_2.1-2          

Thank you

**Comment by esiegel** [comment]
Can you include the code that you are running when using 10x data when this is failing?  Given that Seruat5 was just released maybe there is a change with how the data is stored.

Additionally, just want to let you know that technically, converting non 10x data is a violation of our [End User License Agreement](https://www.10xgenomics.com/legal/end-user-software-license-agreement)

**Comment by sonalhenson** [comment]
Hi Eric, 
The code I used was exactly the same as in the demo document in your Readme, using the test dataset used in the document. 
Also, my data is from a 10X library - just sequenced on nanopore. 
Many thanks.

**Comment by esiegel** [comment]
Thanks for the info.  Seems that this issue comes with Seurat 5.  The format that they use to store the data has changed.

Here is a temporary solution until I commit the fix:

```R
# This will fetch the gene expression assay, which will be be of class `Assay5` when using Seurat5
assay5 <- seurat_obj[["RNA"]]

# convert the assay to the old version and store this back into the seurat object
seurat_obj[["RNA"]] <- suppressWarnings(as(object = assay5, Class = 'Assay'))

# now you should be able to create the file
create_loupe_from_seurat(seurat_obj, output_name = "louper_test")
```

**Comment by sonalhenson** [comment]
Thank you very much for posting this temporary fix. It generates a .cloupe file, however, the file won't open in the Loupe browser (68MB size). I don't get an error from the Loupe browser - it just won't finish loading. Here again, I'm testing with the demo data and not my own data. I am able to open a cellranger-generated .cloupe file in Loupe so the issue can't be with my Loupe browser. Any ideas on how to resolve this?

**Comment by esiegel** [comment]
Are you using loupe browser 7 are newer.  That is required for viewing any cloupe file generated from loupeR

**Comment by sonalhenson** [comment]
That was it!! I can open the .cloupe files in Loupe Browser 7 (I was using v6). Apologies, I was under the impression I had the latest version of the browser. Thanks for all your help.
