### ISSUE TITLE
loupeR with SingleCellExperiment

### ISSUE THREAD

**Issue by NadineBestard** [10XGenomics/loupeR#27]
This is not a big issue, but a small enhancement request.  Would be nice to add a function equivalent to `create_loupe_from_seurat() ` but to create a loupe file from a SingleCellExperiment (sce) from Bioconductor. Or at least add some comments about it in the manual. Having a look at the expected input from `create_loupe` it was quite easy to work around thought. So I leave here the code I used.

```
## the cluster selection has some requirements, modify the function to work with sce 
select_clusters_sce <- function(obj) {
  # create list
  clusters <- list()
  # Use all factors and character vectors from colData
  for (name in names(colData(obj))) {
    data <- colData(obj)[[name]]
    
    if (is.factor(data)) {
      clusters[[name]] = data
    } else if (is.character(data)) {
      clusters[[name]] = factor(data)
    }
  }
  return(clusters)
}

## The other steps are more straightforward
# extract gene expression
counts <- assay(sce, "counts")
# dimesional reduction - I did not bother making the function as usually there are very few reduced dims calculated, just add here any other desired reduced dimension.
red_dim <- list(UMAP=reducedDim(sce, "UMAP"), TSNE=reducedDim(sce,"TSNE") 

## Construct the loupe file
create_loupe(counts, clusters=select_clusters_sce(sce), projections = red_dim)
```

**Comment by esiegel** [comment]
I'm glad you were able to figure out how to get the conversion to work.  I'm not really too familiar with `SingleCellExperiment` and the way things are structured.  Do you think the code that you provided would work with all SCE datasets?  As a non authority I worry about adding a semi-functioning method.

The man pages for `create_loupe` are as follows:

```
\item{count_mat}{A sparse dgCMatrix}
\item{clusters}{list of factors that hold information for each barcode}
\item{projections}{list of matrices, all with dimensions (barcodeCount x 2)}
```

Do you think the wording should be updated here to make it clearer?

**Comment by NadineBestard** [comment]
The description in the man for create_loupe is clear. 
By adding a note in the "manual" I had in mind the  [10x manual](https://www.10xgenomics.com/support/software/loupe-browser/tutorials/introduction/lb-louper), or other 10X info. It says everywhere "generate Cloupe from Seurat" and I was not sure until having a deeper look at the functions if it would be possible to adapt the code to work with other structures than Seurat.

The code I provided in the function is very general and should work for any `sce`. As you may notice the rest is hard coded, so it would work if the counts are in `counts` (that is the default name) and the reduced dimensions are called `TSNE` and `UMAP` (by default UMAP and TSNE are stored like this, but maybe someone only has one of them, or any other that are not these).

**Comment by esiegel** [comment]
Thanks for the update.  I will pass along your message to the documentation team for the manual.  I agree that it is a bit confusing.  It is true that our MVP was mostly targeting Seurat, with the `create_loupe` lower level method intentionally being generic to allow non-Seurat users interoperability.

I'd be open for a PR that adds a `create_loupe_from_sce`.
