### ISSUE TITLE
Issue with creating the loupe file - Louper executable failed: status code 1

### ISSUE THREAD

**Issue by marck1198** [10XGenomics/loupeR#29]
Hello,

I was trying out the [Demo Notebook](https://colab.research.google.com/github/10XGenomics/loupeR/blob/main/misc/tutorials/5k_mouse_brain.ipynb) by copying the code into RStudio. However, whenever I attempted to create .cloupe files from Seurat objects, I would encounter an error.

Output:

> create_loupe_from_seurat(seurat_obj, output_name = "louper_test")
2023/12/12 12:07:59 extracting matrix, clusters, and projections
2023/12/12 12:07:59 selected assay: RNA
2023/12/12 12:07:59 selected clusters: active_cluster orig.ident RNA_snn_res.0.5 seurat_clusters
2023/12/12 12:07:59 selected projections: umap
2023/12/12 12:07:59 validating count matrix
2023/12/12 12:07:59 validating clusters
2023/12/12 12:07:59 validating projections
2023/12/12 12:07:59 creating temporary hdf5 file: C:\Users\mv\AppData\Local\Temp\RtmpIBrWva\file78c07bfee36.h5
2023/12/12 12:08:04 invoking louper executable
2023/12/12 12:08:04 running command: "C:\Users\mv\AppData\Roaming\R\data\R\loupeR\louper.exe create --input=C:\Users\mv\AppData\Local\Temp\RtmpIBrWva\file78c07bfee36.h5 --output=C:\Users\mv\Desktop\louper_test.cloupe"
Usage:
	louper create --input=INPUT --output=OUTPUT_PATH [-f | --force] [--name=NAME] [--description=DESCRIPTION]
	louper -h | --help
	louper --version
Error in create_loupe(counts, clusters = clusters, projections = projections,  : 
It looks like there was an issue with creating the loupe file. For further information, please see the documentation: 10xgen.com/louper
Louper executable failed: status code 1

I could successfully run the rest of the code from the notebook (even producing the plot). When running create_bugreport_from_seurat(seurat_obj), I get this:

Metadata:

tool: loupeR
tool_version: 1.0.1
os: Windows 11 x64 (build 22621)
system: x86_64-w64-mingw32/x64 (64-bit)
language: R
language_version: 4.3.2
extra:
     loupeR_seurat_version: 5.0.1
     loupeR_seurat_object_version: 5.0.1
     loupeR_hdf5r_version: 1.3.8
     loupeR_hdf5_version: 1.8.16

Selections:

selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    RNA_snn_res.0.5
    seurat_clusters
selected projections:
    umap

Matrix Sampling:

feature count: 32285
barcode count: 7377
feature sampling:
    Dennd2c
    5730460C07Rik
    Phldb2
    Yif1b
    Pkmyt1
    D130009I18Rik
    Gm47922
    Gm38839
    CR974586.5
    Olfr291
barcode sampling:
    CTCATTAGTAACAGTA-1
    GTTTACTCAACCCTCT-1
    CCGATGGTCATGCCCT-1
    TGAGCATAGATAGTGT-1
    TTACAGGTCCGTGCGA-1
    CAGTTAGCAAGTCCAT-1
    GAATCACGTCTGTGTA-1
    GCGTTTCCACCCTGTT-1
    GTCTAGAGTGCCTATA-1
    AACAGGGTCGGCAGTC-1

Validation:

    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)

If anyone has any suggestions on what I could do to fix this, I would greatly appreciate it.

Thanks in advance.

**Comment by marck1198** [comment]
Managed to fix it. I moved my Working Directory to the general Documents folder rather than a separate folder, and it appears to have fixed the problem. I reckon it might be due to either hdf5 not having access to this particular folder.

**Comment by esiegel** [comment]
Would you be able to run the louper executable directly?  It is logged to stdout when you invoke create_loupe.

Something like this:

```
C:\Users\mv\AppData\Roaming\R\data\R\loupeR\louper.exe create --input=C:\Users\mv\AppData\Local\Temp\RtmpIBrWva\file78c07bfee36.h5 --output=C:\Users\mv\Desktop\louper_test.cloupe
```

You aren't the first to hit an issue like this and it would be super helpful to figure out exactly what is going on.

**Comment by marck1198** [comment]
Hey, I figured out why it wasn't working.

The folder I had initially as my working directory had spaces and - in it's name. After changing the name, it began to work. This explains why the default document file worked as there was no space or  - to mess up the python script.

Glad we got to the bottom of the glitch.
