### ISSUE TITLE
It looks like there was an issue with creating the loupe file.

### ISSUE THREAD

**Issue by Jyng321** [10XGenomics/loupeR#30]
Hi all,
currently, I have a problem in exporting Seurat project into .cloupe file for Loupe app using LoupeR package.
By running the guilting on test data, I did not have any problem. (https://github.com/10XGenomics/loupeR/blob/main/R/lib.R).
However, when I tried on my data (multiome ATAC GEX Seq), it showed an error in creating the loupe file. (Please see attachment).
Does anyone have an idea? I would appreciate it. Thanks.

```{r}
DefaultAssay(e145) <- "RNA"
create_loupe_from_seurat(e145, output_name = "e145_DE_R")
```
2023/12/15 13:18:53 extracting matrix, clusters, and projections
2023/12/15 13:18:53 selected assay: RNA
2023/12/15 13:18:53 selected clusters: active_cluster orig.ident wsnn_res.0.8 seurat_clusters celltype
2023/12/15 13:18:53 selected projections: umap.rna umap.atac wnn.umap
2023/12/15 13:18:53 validating count matrix
2023/12/15 13:18:53 validating clusters
2023/12/15 13:18:53 validating projections
2023/12/15 13:18:53 creating temporary hdf5 file: C:\Users\nguyeh4w\AppData\Local\Temp\RtmpWwRPKc\filecaa81a7e627a.h5
2023/12/15 13:18:54 invoking louper executable
2023/12/15 13:18:55 running command: "C:\Users\nguyeh4w\AppData\Roaming\R\data\R\loupeR\louper.exe create --input=C:\Users\nguyeh4w\AppData\Local\Temp\RtmpWwRPKc\filecaa81a7e627a.h5 --output=C:\Users\nguyeh4w\Data\AG Tuoc offline\Projects\2023-10-16_SingleCellATAC\Analysis_Results\e145\Duy's code\e145_DE_R.cloupe"
Usage:
	louper create --input=INPUT --output=OUTPUT_PATH [-f | --force] [--name=NAME] [--description=DESCRIPTION]
	louper -h | --help
	louper --version
Error in create_loupe(counts, clusters = clusters, projections = projections,  : 
  
It looks like there was an issue with creating the loupe file. For further information, please see the documentation: 10xgen.com/louper

Louper executable failed: status code 1

**Comment by esiegel** [comment]
This seems to be the same issue that #29 was dealing with.  I need to investigate, but it looks like having spaces in the name or path is causing problems on windows.

**Comment by esiegel** [comment]
This should be fixed now.  PR can be seen here: #31
