### ISSUE TITLE
counts_matrix_from_assay() function doesn't exist

### ISSUE THREAD

**Issue by AmyOlex** [10XGenomics/loupeR#32]
In the README for this package there are the following lines to extract the count data for the create_loupe() function:

\# get counts matrix from either the old or newer formats of assay
counts <- counts_matrix_from_assay(assay)

However, after loading the LoupeR package it says this function doesn't exist.  In the tutorials the following is utilized, which does work:

\# Get the count matrix from a Seurat object:
count_mat <- seurat_obj@assays$RNA@counts

**Comment by esiegel** [comment]
What version of `loupeR` do you have installed?  This function was added here #23, but there hasn't been a new release since.  You would have to install the latest version to get this function.

```
remotes::install_github("10XGenomics/loupeR")
loupeR::setup()
```

I will make a new update shortly.

**Comment by esiegel** [comment]
Releae v1.0.2
