### ISSUE TITLE
create_loupe_from_seurat() error: Barcodes should begin with base pairs and end with an optional hyphen and suffix

### ISSUE THREAD

**Issue by liangyuli12138** [10XGenomics/loupeR#35]
Hi, I have met the same problem in   #8 . just like this:
```R 
2024/01/31 19:35:59 extracting matrix, clusters, and projections
2024/01/31 19:36:00 selected assay: RNA
2024/01/31 19:36:00 selected clusters: active_cluster orig.ident CellType_Category Manuscript_Identity Subclass_Cell_Identity Disease_Identity Subject_Identity Library_Identity
2024/01/31 19:36:00 selected projections: umap
2024/01/31 19:36:00 validating count matrix
2024/01/31 19:36:17 validating clusters
2024/01/31 19:36:17 validating projections
2024/01/31 19:38:10 validating input file: /tmp/Rtmprv06ee/file162c3d8c257d.h5
2024/01/31 19:38:12 Dataset "/matrix/barcodes": There is an issue with the formatting of your barcodes.
Barcodes should begin with base pairs and end with an optional hyphen and suffix.
For further information, please see the documentation: 10xgen.com/louper
Error in create_loupe(assay@counts, clusters = clusters, projections = projections,  :

It looks like there was an issue with creating the loupe file. For further information, please see the documentation: 10xgen.com/louper

Louper executable failed: status code 1
Calls: create_loupe_from_seurat -> create_loupe
Execution halted
```

I try to Rename cell names but not work, could you tell me how to fix it ?
#=============
This is my `create_bugreport_from_seurat()` result:
```R

Metadata:

tool: loupeR
tool_version: 1.0.1
os: CentOS Linux 7 (Core)
system: x86_64-pc-linux-gnu (64-bit)
language: R
language_version: 4.2.1
extra:
     loupeR_seurat_version: 4.3.0
     loupeR_seurat_object_version: 5.0.1
     loupeR_hdf5r_version: 1.3.6
     loupeR_hdf5_version: 1.10.7

Selections:

selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    CellType_Category
    Manuscript_Identity
    Subclass_Cell_Identity
    Disease_Identity
    Subject_Identity
    Library_Identity
selected projections:
    umap

Matrix Sampling:

feature count: 42628
barcode count: 243472
feature sampling:
    RBM14
    MARK1
    LINC00857
    ENSG00000259536
    ENSG00000241183
    WDR24
    HOTTIP
    TRMT12
    ENSG00000273138
    LINC00476
barcode sampling:
    TCACAAGGTATGAATG-051I_a
    CTTCTCTTCAGTGCAT-051I
    CGGAGCTGTTACAGAA-59I
    CGCTGGACATAAGACA-92C
    TTATGCTCAGCAGTTT-158I_b
    GCTTGAAAGCTAACTC-133C_a
    GCATGATTCTAGAGTC-209I_a
    CTACACGACGCTCTTC-040I_b
    GTAACGTCAAGTTGTC-208C
    AGATTGCGTTCCGGCA-145I_a

Validation:

    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
```
Thanks a lot

_Originally posted by @liangyuli12138 in https://github.com/10XGenomics/loupeR/issues/8#issuecomment-1920391105_

**Comment by esiegel** [comment]
As stated in the other ticket, all data must originate from a 10x experiment.  Looking at the barcode sampling in the bugreport it doesn't seem like all of those are valid.  For example, where does this come from `CTACACGACGCTCTTC-040I_b`?

**Comment by liangyuli12138** [comment]
Hi, @esiegel ,Thanks for your reply.

I downloaded the data from GSE136831(https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136831), which the publication is on https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7439502/. The author declare that the scRNA data was generated by 10X chromium single-cell platform, just like this :

![image](https://github.com/10XGenomics/loupeR/assets/41354365/d63c644a-fb5f-418d-a670-a9e6b96646c6)

-----------------------------------------------------------------------------------------------------------------------------------------
About the cellnames, the origin cell barcodes from GEO data were just like this : `001C_AAACGGGAGACTAAGT, 040I-b-CTACACGACGCTCTTC`. I gusted `001C` and `040I-b` were sample names ,which added by the author.

![image](https://github.com/10XGenomics/loupeR/assets/41354365/cf8441d6-4793-4a50-8c68-1d8f053edb03)

-----------------------------------------------------------------------------------------------------------------------------------------
I have read the instruction for LoupeR carefully, so I change the cell name before using `create_bugreport_from_seurat()`.
This is my code 
```R
newcellname <- sapply(strsplit(colnames(dat),"_"),function(x){
    ifelse(length(x)>2, paste0(x[3],"-",x[1],"_",x[2]), paste0(x[2],"-",x[1]))
})
dat <- RenameCells(dat,new.names=newcellname)
create_loupe_from_seurat(dat)
```
after this `040I-b-CTACACGACGCTCTTC` was changed into `CTACACGACGCTCTTC-040I_b`, but it doesn't work

**Comment by esiegel** [comment]
Maybe the authors ended up doing something like this: https://github.com/sdparekh/zUMIs/wiki/Starting-from-demultiplexed-fastq-files , which the zUMI docs show produces new randomly generated barcodes?  Maybe reach out the authors of the paper to see if they added anything?

At this point there isn't a way to generate a Loupe file if there are invalid barcodes.

**Comment by esiegel** [comment]
Closing for now as I don't think there is anything i can do.

**Comment by bc2zb** [comment]
Question regarding this issue and related issues, seems like a suffix is no longer supported for exporting to loupe? I was having issues exporting until I removed suffixes from my cell names, and then it had no issues, even though some barcodes were change from `[BARCODE]-1` to `[BARCODE-2]`.

**Comment by gmjoseph** [comment]
> Question regarding this issue and related issues, seems like a suffix is no longer supported for exporting to loupe? I was having issues exporting until I removed suffixes from my cell names, and then it had no issues, even though some barcodes were change from `[BARCODE]-1` to `[BARCODE]-2`.

Hi @bc2zb, in the latest release (1.1.2 as of writing this comment), we've reworked how prefixing and suffixing is handled to better support these kinds of usecases: https://github.com/10XGenomics/loupeR?tab=readme-ov-file#barcode-formatting
Loupe has also been updated (to 8.1, available here: https://www.10xgenomics.com/support/software/loupe-browser/latest), which should also accept the formatting specified in the README.
If you're still running into issues, please open a new issue and we can take a look at it.
