### ISSUE TITLE
LoupePy

### ISSUE THREAD

**Issue by wangjiawen2013** [10XGenomics/loupeR#36]
Hi,
Happy to see that loupeR which can convert seurat object to cloupe. Do you plan to develop loupePy to convert scanpy object to cloupe ? Or some python packages to convert mtx data to cloupe directly ?

**Comment by esiegel** [comment]
It definitely is something I've thought about, but there isn't any specific timelines that we have discussed.  `loupeR` works by converting a dataset into an `hdf5` file as an interchange file that is then read by the `louper` executable.  If someone wants to add support for something like scanpy this would be the way forward.

**Comment by esiegel** [comment]
Feel free to open if you have more comments here
