### ISSUE TITLE
Error in self$set_size(size) : HDF5-API Errors:     error #000: /tmp/hdf5-20240208-26272-vz5oib/hdf5-1.14.3/src/H5T.c in H5Tset_size(): line 2317: size must be positive

### ISSUE THREAD

**Issue by whitneyt1** [10XGenomics/loupeR#37]
Hello, I am getting this error when running this on my Visium object.
I have checked that the seruat object version is >5

<img width="790" alt="image" src="https://github.com/10XGenomics/loupeR/assets/46573884/36cc400b-796f-4b56-8d90-659dde890237">

my code is:
`for (i in sample_IDs_list) {
  print(i)
  filename=paste0(i, "_anno")
  #print(filename)
  tmp_obj=obj_list[[i]]
  print(Version(tmp_obj))
  #tmp_obj<-UpdateSeuratObject(tmp_obj)
  create_loupe_from_seurat(obj=tmp_obj, 
                          output_dir="/Box/Spatial_Data/Annotated_cloupe",
                          output_name=filename)
  break
}`

When I inspect the counts slot via tmp_obj@assys$RNA@counts I can see a matrix with counts. How do I extract this matrix?

**Comment by whitneyt1** [comment]
`> create_bugreport_from_seurat(tmp_obj)

Metadata:

tool: loupeR
tool_version: 1.0.2
os: macOS Big Sur 11.2
system: x86_64-apple-darwin17.0 (64-bit)
language: R
language_version: 4.2.1
extra:
     loupeR_seurat_version: 5.0.0
     loupeR_seurat_object_version: 5.0.1
     loupeR_hdf5r_version: 1.3.9
     loupeR_hdf5_version: 1.14.3

Selections:

selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    Graph.based
    Graph.based.mod
    ROIs
    ROIs.mod
    Sample_ID
    Patient_ID
    Resection_Site
    Histology
    Gender
    Race
    Smoking_Hx
    Driver_Mutation
    Co_Occuring_Mutations
    Tx_Timepoint
    Treatment_History_At_Resection
    Treatment_Annotation
    Treatment_Analysis
    TKI
    Dx_TNM_Stage
    Dx_Clin_Stage
    Sx_TNM_Stage
    Sx_Clin_Stage
    Site
    Comment
    Sample_ID.mod
    Temp_ID
    Cell_Name
    V3
    V4
    position
    clone
    SCT_snn_res.0.8
    seurat_clusters
    Top.Prediction
    integrated_snn_res.0.5
    itx_seurat_clusters
selected projections:
    umap

Matrix Sampling:

feature count: 36601
barcode count: 3580
feature sampling:
    TRIM16
    MRPS11
    CYP11B2
    PTDSS1
    QRICH2
    RSU1
    CXCL2
    MYCBP2
    EGFLAM
    EFTUD2
barcode sampling:
    CACTGTCCAAGTGAGA-1_1
    TTGTAAGGACCTAAGT-1_1
    TCGTAAGACGACATTG-1_1
    TGAGAGATTTACCACG-1_1
    ACGATCATCTTGTAAA-1_1
    CATGATACGGTGAAAC-1_1
    ATCCACATCGACAGAA-1_1
    CCTGTCACCCGGGCTC-1_1
    TAATACTAGAACAGAC-1_1
    GCTCCGGACGTTGATA-1_1

Validation:

    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
Warning message:
Layer ‘counts’ is empty `

**Comment by esiegel** [comment]
`loupeR` is using logic like this:

```R
assay <- Seurat::GetAssay(tmp_obj, assay="RNA")
count_mat <- assay$counts
```

This logic seems to work with the datasets that I've seen, but I admit that I'm still trying to understand how Seurat v5 datasets are stored.  I see you are using `tmp_obj@assys$RNA@counts` and I am using `tmp_obj@assys$RNA$counts`.  Do you have insights on the difference?

**Comment by whitneyt1** [comment]
Hi @esiegel  I tried both `RNA$counts` and `RNA@counts` and received the same error, 

however, when I ran `tmp_assay=Seurat::GetAssay(tmp_obj, assay='RNA')` as part of using create_loupe and manually extracting counts, clusters, and predictions  i received the error `Error in assays : object 'assays' not found` so perhaps that is part of the problem. 


`for (i in sample_IDs_list) {
  print(i)
  filename=paste0(i, "_anno")
  #print(filename)
  tmp_obj=obj_list[[i]]
  tmp_clusters<-select_clusters(tmp_obj)
  tmp_projections<-select_projections(tmp_obj)
  tmp_assay=Seurat::GetAssay(tmp_obj, assay='RNA')
  tmp_count_mtx<assays$counts
  create_loupe(
    count_mat = tmp_count_mtx,
    clusters = tmp_clusters,
    projections = tmp_projections,
    output_dir = './Box/Spatial_Data/Annotated_cloupe/',
    output_name = filename,
    seurat_obj_version = '5.0.1'
  )
  break
}`

**Comment by whitneyt1** [comment]
<img width="633" alt="Screenshot 2024-02-12 at 12 30 00 PM" src="https://github.com/10XGenomics/loupeR/assets/46573884/ed355ebf-6925-461c-85aa-1d6200ba9f26">

**Comment by esiegel** [comment]
If your seurat object isn't too large, can you share it somewhere?  Also, interested in what class `tmp_assay=Seurat::GetAssay(tmp_obj, assay='RNA')` is.

**Comment by whitneyt1** [comment]
@esiegel what is the best way to share? thanks!

**Comment by esiegel** [comment]
If you have google drive or dropbox that would be great.  You can send me an email with the private link here `eric.siegel@10xgenomics.com` if you don't want it to be visible by others.

**Comment by esiegel** [comment]
So the issue is that some of the clusters are missing level information.  They either have zero levels, or have a single level that is the empty string.  This is leading to a failure to write the intermediate hdf5 file because it is trying to write a zero length array which is not allowed.

I will add logic to make this issue less likely to happen and add validation, but for now you can do the following

```R
  tmp_clusters<-select_clusters(tmp_obj)

  good_clusters <- sapply(tmp_clusters, function(f) {
    if (length(levels(f)) == 0) {
      return(FALSE)
    }
    max(as.numeric(lapply(levels(f), nchar))) > 0
  })

  tmp_clusters <- tmp_clusters[good_clusters]
```

**Comment by whitneyt1** [comment]
Thank you!!!!
