### ISSUE TITLE
Support for Exporting Spatial Plots to Loupe Browser Format

### ISSUE THREAD

**Issue by fmbetul** [10XGenomics/loupeR#38]
Dear 10X Team,

I've been using loupeR for exporting Seurat objects to Loupe Browser but noticed it only exports UMAP plots. My work involves 10X Visium spatial data, and having the spatial plots in Loupe Browser is crucial for me.

Is there a way to include spatial plots in the export process, or plans to add this feature? Any advice or workaround would be greatly appreciated.

Thanks for your support and the great work on loupeR.

Best,
Betul

**Comment by esiegel** [comment]
This is definitely on our roadmap, but isn't currently implemented.  Sadly, there isn't a work around.

**Comment by esiegel** [comment]
Are you hoping to import a full scale microscope image and a bunch of spots?  Are the spots the same as what is found in the outs directory of a visium experiment.

**Comment by fmbetul** [comment]
Thank you for your prompt response, Eric. My primary goal is to make Seurat analysis results accessible to individuals who may not be proficient in coding, allowing them to explore the data further on their own.

To address the immediate need for sharing Visium analysis results with collaborators who may not be familiar with coding, I've taken the initiative to develop a basic R Shiny application. This application is designed to generate plots similar to the LinkedFeaturePlot and LinkedDimPlot.

For those interested, the application can be accessed here:  https://github.com/fmbetul/Bioinformatics/blob/main/visium_shiny_app.R 

I hope it proves to be helpful for others in the community seeking an alternative until the full-scale Loupe Browser solution becomes available. I eagerly await the integration of this feature into loupeR and appreciate all the efforts your team is putting into expanding the tool's capabilities.

Thanks again for your support and the excellent work on loupeR.

Betul
