### ISSUE TITLE
Issue with Spatial Projection with Visium CytAssist data

### ISSUE THREAD

**Issue by Streisenberg** [10XGenomics/loupeR#4]
Hello,

Firstly, I'd like to express my gratitude for this excellent package and idea. I am working with Spatial Transcriptomics (ST) data and trying to convert my ST object to a Loupe file. I have successfully created a loop file with the UMAP projection by my chosen clusters. 

However, it seems I can't utilize the Spatial projection since I couldn't provide the Image file of my Seurat object. Moreover, I can't access the spatial projection for the Protein assay data either. I am sorry if I overlooked but I couldn't find any instructions or code examples in the documentation regarding this. Any assistance on this would be greatly appreciated.

Thank you in advance.

**Comment by phoebee-h** [comment]
Hi,
I think LoupeR is not supported for the other assays now, except for "3’ Single Cell Gene Expression". 
See the "Prerequisites" part: 
https://www.10xgenomics.com/support/software/loupe-browser/tutorials/lb-louper#prerequisites

But I also wish it could apply to the others too.

**Comment by esiegel** [comment]
Thank you @phoebee-h for providing that link and yes, currently we only support 3' Gene Expression datasets.  Spatial in particular is a can of works as supporting all the various microscopy image formats can get pretty burdensome.  I can definitely image a future though where we do support some subset.
