### ISSUE TITLE
is it possible to create a loupe object with multiple assays?

### ISSUE THREAD

**Issue by whitneyt1** [10XGenomics/loupeR#40]
Thank you for all of your help! 
I currently have two assays that I'd like to look into with loupe, one is the normal count assay, and one is the predictions of cell composition for visium spots. The format of the assay is similar to the counts matrix, with spot barcodes x cell type with each cell having a score, also a lot of 0s, similar to count matrix. Is it possible to extract both of these assays simultaneously? 

Thanks!

**Comment by esiegel** [comment]
A Loupe file only supports a single count matrix and doesn't have a mechanism for including the additional `barcode X cell Type` matrix of data.
