### ISSUE TITLE
Creating Loupe from Seurat with spatial information

### ISSUE THREAD

**Issue by dylanwudy** [10XGenomics/loupeR#41]
Hi,
I want to create the loupe file based on my processed Seurat object with spatial infomation, while I do not found the option of loading spatial location in the create_loupe_from_seurat or any relative function. How am I suppose to create a loupe object with the spatial information and combine with my edited metadata?

**Comment by esiegel** [comment]
Creating a loupe file with spatial information is on the roadmap, but currently not supported.
