### ISSUE TITLE
Merge annotated spatial information from 10X Visium into cloupe visualizer

### ISSUE THREAD

**Issue by whitneyt1** [10XGenomics/loupeR#42]
Basically, our issue is that we had some data loss and lost the H&E image files and are now reliant on the cloupe outputs to visualize the tissue. 

1. Is there a way to extract the high resolution image in the cloupe file? It is higher resolution than the hiresimage.png file. 
or 
2. Is there a way for me to upload seurat meta features into an existing cloupe file? For example extract a table with the visium spot barcodes x annotated features from the Seurat object then upload/merge it with the cloupe file?

In reviewing issue  #38, it seems like 2. is not currently supported, but in case there is a way to achieve 1. I thought i'd open another issue.

Thank you so much!!

**Comment by esiegel** [comment]
Just to speak to your first point, there isn't currently a way to extract the full scale image from the loupe file and yes it should have better resolution
