### ISSUE TITLE
loupeR in a Docker/Singularity container

### ISSUE THREAD

**Issue by SergejN** [10XGenomics/loupeR#43]
Dear 10X team,
I was wondering whether it would even be legal to include `loupeR` into a Docker container to run a Nextflow pipeline and output the Cloupe file (from a Seurat object, so the cloupe files generated by CellRanger are not what I mean).
If I interpret the license correctly (point 3), it is not
https://github.com/10XGenomics/loupeR/blob/main/LICENSE

I would be thankful for any advice how this can be solved (if it can). If the only way is to ask the end user of the pipeline to install `loupeR` and run `setup()`, then this is the way to go. 

thanks a lot!
Sergej

**Comment by esiegel** [comment]
Maybe it's best to reach out to support@10xgenomics.com .

**Comment by dylanwebster** [comment]
Hello to anyone reading this issue who has a similar need. We have a path to enable use cases like the one SergejN raised here. Please reach out to support@10xgenomics.com and/or myself (dylan.webseter@10xgenomics.com) if you would like to discuss further!
