### ISSUE TITLE
Feature request: Import cluster colors

### ISSUE THREAD

**Issue by kloot** [10XGenomics/loupeR#46]
May I nominate this feature - ideally via a vector or list of hex values external to Seurat, solely to avoid Seurat's choice of not-so-easy-to distinguish colors.

Thanks in advance!

**Comment by gmjoseph** [comment]
Hi @kloot

Thanks for filing this feature request. We're currently discussing it as a team - I can let you know the status of it once we've come to a decision.

**Comment by esiegel** [comment]
Closing as the feature request has been noted.
