### ISSUE TITLE
Creat Loupe file for Visium HD data

### ISSUE THREAD

**Issue by LI-Yan-Ming** [10XGenomics/loupeR#47]
Hi, thank you for developing the tool!
I am trying to create a Loupe file from a Seurat object of Visium HD data. However, I got an error "Barcodes should begin with base pairs and end with an optional hyphen and suffix". The thing is, with visium HD, the barcode doesn't format like that. Below is what the barcodes look like. Do you have any thoughts on how to fix it? Thank you so much!!

s_002um_01765_02581-1
s_002um_02207_02353-1
s_002um_01652_02243-1
s_002um_02278_00850-1
s_002um_01548_00633-1
s_002um_02148_02515-1
s_002um_02684_02407-1
s_002um_01016_01060-1

**Comment by gmjoseph** [comment]
Hi @LI-Yan-Ming

Thanks for filing this issue. I believe in order to get this working, we're going to need to make an update on our end, followed by an updated release of LoupeR.

I'll follow up again once we've started working on this.
