### ISSUE TITLE
Creating Loupe file from Seurat fails in R 4.4.0

### ISSUE THREAD

**Issue by astark4** [10XGenomics/loupeR#48]
The function create_loupe_from_seurat() fails in R 4.4.0 (working fine in previous versions) when referencing  .make_numeric_version with the following error:

extracting matrix, clusters, and projections
Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double)

**Comment by NeginValizadegan** [comment]
Same problem here

**Comment by gmjoseph** [comment]
Thank you for reporting the issue, we're looking into it. Once we have made progress on it we will follow up with an update.

**Comment by toedling** [comment]
The solution is to replace the line:
if (packageVersion("Seurat") >= 5)
by
if (packageVersion("Seurat")[[1,1]] >= 5)
in the file "util.R".  The function packageVersion now returns a special list object which cannot be compared directly with a number.

**Comment by lask99** [comment]
Does anyone have a solution to this yet? I get the exact same message

**Comment by astark4** [comment]
> The solution is to replace the line: if (packageVersion("Seurat") >= 5) by if (packageVersion("Seurat")[[1,1]] >= 5) in the file "util.R". The function packageVersion now returns a special list object which cannot be compared directly with a number.

This works if you know how to download the source and install into R from a local tar.xz file. The most user-friendly way of doing this is to use 7-zip to edit the loupeR/R/util.R file within the tar file

**Comment by lask99** [comment]
I have tried changing the code on the util.R file and it still does not work in R - same message appears

**Comment by gmjoseph** [comment]
@lask99 no updates yet - is it possible to use an older version of R studio as a workaround in the meantime?
