### ISSUE TITLE
HDF5 error after joining multi-layer seurat object

### ISSUE THREAD

**Issue by brigidar** [10XGenomics/loupeR#49]
I combined my multi-layer seurat object as recommended, but when I try to export it I still get an issue at the hdf5r step. I have hdf5 installed and the package too. this is the error I get.
Error in x$Priority : $ operator is invalid for atomic vectors

**Comment by gmjoseph** [comment]
Hi @brigidar, if possible, could you please share the full set of steps that got you to that error? Thanks!

**Comment by esiegel** [comment]
Closing the issue as we haven't received a response.  If you are still dealing with this issue please reopen.
