### ISSUE TITLE
Is the category number restricted?

### ISSUE THREAD

**Issue by phoebee-h** [10XGenomics/loupeR#5]
Hi,
Thanks for developing this amazing package. I wonder whether the cell labeling is still restricted as in the old Loupe package? (As I remember, I think the old one could only accept less than 100 types)

**Comment by esiegel** [comment]
As is discussed in this issue #2 each cluster is limited to a maximum of 32768 groupings.  That being said, I can't recommend having this many groups in a cluster.  In Loupe the coloring would be impossible to distinguish groups, also UI performance might have issues though I personally haven't tried.

If asking about a limit to the number of clusters, I do not believe there is one.

**Comment by phoebee-h** [comment]
OK. 
Thank you. I think 32768 is enough, better than the old one.

**Comment by esiegel** [comment]
Seems like this answered your question.  Going to close this.  Feel free to reopen if need be.
