### ISSUE TITLE
Keep continuous features created in Seurat

### ISSUE THREAD

**Issue by brigidar** [10XGenomics/loupeR#50]
Hi,
I have a seurat object where I have calculated cell cycle scores for each cell, but when I convert it to a cloupe object I lose it as well as other continuous variables. Is there a way to keep them so that my collaborators can visualize them?
Thanks

**Comment by dylanwebster** [comment]
Hi @brigidar, we're aware of this limitation of Loupe Browser, and are considering adding support for importing and plotting non-integer counts in a future Loupe version.  I apologize that the only workaround for now is to adjust scores to be scaled to positive integers—which we realize is not ideal. We hope to be able to write back when we've added this capability!

**Comment by lweasel** [comment]
+1, this would be a very helpful addition to loupeR / Loupe Browser.

**Comment by esiegel** [comment]
Closing for now, as the feature request has been noted.
