### ISSUE TITLE
Error in creating Loupe file: Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) :    invalid non-character version specification 'x' (type: double)

### ISSUE THREAD

**Issue by rln0005** [10XGenomics/loupeR#52]
Hi 10x Team, 

First off, thank you for creating the LoupeR function to make working with Seurat + Loupe easier! 

Unfortunately, I keep getting the same error:
**"Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double)"** 

Here is a broad overview my pipeline: 
1. SpotClean to clean up the unfiltered data
2. Convert from 'Summarized Experiment' (SpotClean pipeline) to Seurat Object
3. Seurat analysis--SCTransform, RunPCA, FindNeighbors, FindClusters, RunUMAP (outputs a 'Large Seurat' object)
4. LoupeR: create_loupe_from_seurat 

I'm really not sure what to make of this error message. Any suggestions? Thanks in advance. 

Rebecca

**Comment by gmjoseph** [comment]
Hi again @rln0005 , this issue should now be resolved with the latest release (V1.1.1) of LoupeR. Thanks again for the reporting the issue.
