### ISSUE TITLE
Barcodes should begin with base pairs and end with an optional hyphen and suffix

### ISSUE THREAD

**Issue by josegarciamanteiga** [10XGenomics/loupeR#53]
Dears,
The error in the title is thrown with this debugging after calling
`create_bugreport_from_seurat(cds)`

```
Metadata:
  
tool: loupeR
tool_version: 1.1.0
os: CentOS Linux 7 (Core)
system: x86_64-conda-linux-gnu (64-bit)
language: R
language_version: 4.3.3
extra:
     loupeR_seurat_version: 5.0.3
     loupeR_seurat_object_version: 5.0.2
     loupeR_hdf5r_version: 1.3.10
     loupeR_hdf5_version: 1.14.3
  
Selections:
  
selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    Phase
    old.ident
    RNA_snn_res.0.5
    seurat_clusters
    RNA_snn_res.0.6
    RNA_snn_res.1
    cell.type
    cell.supertype
    RNA_snn_res.1.2
    RNA_snn_res.1.5
    integrated_snn_res.0.5
    integrated_snn_res.0.7
    integrated_snn_res.1
    cell.type2
    pleura.types1
    cell_clusters_ok
    orig.ident_cell_clusters_ok
selected projections:
    umap
  
Matrix Sampling:
  
feature count: 18722
barcode count: 1075
feature sampling:
    SNUPN
    KRT5
    AL355802.2
    CRIPT
    SLC25A13
    SERTAD2
    ANG
    NT5DC3
    CHST13
    TSSC4
barcode sampling:
CAATACGGTTGCTCGG_1
    TACACGATCTGCCAGG_1
    CGCGGTATCCAAACTG_1
    ACGCCGAGTCTCCCTA_1
    ACAGCCGAGTGCGTGA_1
    GGATGTTGTTACGCCG_1
    ACCCACTTCAAAGTAG_1
    ATGGGAGGTACACCGC_1
    CGATCGGCAGATAATG_1
    CTTTCAAGTGAGTAAT_1
  
Validation:
  
    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
```

cds@version
[1] ‘5.0.2’

While for another object no error is thrown with this debug: (which looks pretty similar to me...)

```
Metadata:
  
tool: loupeR
tool_version: 1.1.0
os: CentOS Linux 7 (Core)
system: x86_64-conda-linux-gnu (64-bit)
language: R
language_version: 4.3.3
extra:
     loupeR_seurat_version: 5.0.3
     loupeR_seurat_object_version: 5.0.2
     loupeR_hdf5r_version: 1.3.10
     loupeR_hdf5_version: 1.14.3
  
Selections:
  
selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    Phase
    old.ident
    RNA_snn_res.1
    seurat_clusters
    RNA_snn_res.0.5
    RNA_snn_res.0.4
    cell.type
    cell.supertype
    RNA_snn_res.0.1
    RNA_snn_res.0.2
    RNA_snn_res.0.3
    RNA_snn_res.0.6
    RNA_snn_res.0.7
    RNA_snn_res.0.8
    RNA_snn_res.0.9
    RNA_snn_res.1.2
    RNA_snn_res.1.1
    RNA_snn_res.0.95
    RNA_snn_res.0.99
    RNA_snn_res.1.5
    RNA_snn_res.0.15
    integrated_snn_res.0.5
    integrated_snn_res.0.1
    integrated_snn_res.0.09
    cell.clusters
selected projections:
    umap
  
Matrix Sampling:
feature count: 18758
barcode count: 8005
feature sampling:
    UBL4A
    MEGF8
    APPL2
    ADIPOR2
    NGFRAP1
    PLEK
    XYLB
    FAM91A1
    ZNHIT1
    IL1A
barcode sampling:
    CGCGTTTGTGTCCTCT_1
    TCGTACCAGGATATAC_5
    TGCACCTTCACCCGAG_5
    AGGGATGCAACTGCTA_5
    GATGAGGTCAATAAGG_5
    TGAGAGGTCACTCTTA_5
    CACATTTTCCTCCTAG_5
    GCTTCCATCTAACGGT_3
    TCAGCAAAGATCACGG_5
    TTCTACAGTGAGGGTT_1
  
Validation:
  
    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
> cds2@version
[1] ‘5.0.2’



```

Why is that?
Thanks

```
sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
  
Matrix products: default
BLAS/LAPACK: /home/garciamanteiga.jose/.conda/envs/sceasy/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0
  
locale:
 [1] LC_CTYPE=en_US.utf-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.utf-8        LC_COLLATE=en_US.utf-8
 [5] LC_MONETARY=en_US.utf-8    LC_MESSAGES=en_US.utf-8
 [7] LC_PAPER=en_US.utf-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.utf-8 LC_IDENTIFICATION=C
  
time zone: Europe/Rome
tzcode source: system (glibc)
  
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
  
other attached packages:
[1] Seurat_5.0.3       SeuratObject_5.0.2 sp_2.1-4           loupeR_1.1.0

```

**Comment by schnappi-wkl** [comment]
Hi, you can replace  your count's barcode with the 10x barcode whitelist
see link https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist 
best wishes!

**Comment by josegarciamanteiga** [comment]
I substituted the barcodes with those in the 10x genomics and it worked!!! Thank you! but I do not know why!!!

**Comment by dylanwebster** [comment]
Hi @josegarciamanteiga, I'm from the 10x Genomics software team. Please note that with LoupeR, all data must originate from a 10x experiment; converting non-10x data is in violation of the [license](https://github.com/10XGenomics/loupeR/blob/main/LICENSE).  

In the barcodes that are sampled from your debugs, it looks like those are indeed valid 10x barcodes, so there must be something else going on—perhaps with other barcodes that were not sampled in the debug. To help us track down the root cause, you can email support@10xgenomics.com and we'd be better able to get into the details.

**Comment by josegarciamanteiga** [comment]
Hi Dylan,
Thanks for the info. They should be 10x samples, indeed. I solved the issue
by substituting the barcodes generating the error with the whitelist from
your web as 'Schnappi' suggested just as a workaround since I needed the
cloupe file, but was not trying to violate the license.

However, since this particular dataset was a bit old, I am checking with
the wet lab people the date and versions of the chromium kits they used. Is
it possible that rather old versions have some barcodes that are not
compatible? This dataset is a merged object of three samples and one of
them could be very old.
Thanks again for your help,

Best
Jose



--------------------------------------
Jose M. Garcia Manteiga PhD
Computational Biologist
Center for Translational Genomics and BioInformatics
Dibit2-Basilica, 4A3
San Raffaele Scientific Institute
Via Olgettina 58, 20132 Milano (MI), Italy

Tel: +39-02-2643-9211
e-mail: ***@***.***


Il giorno mar 4 giu 2024 alle ore 19:39 Dylan Webster <
***@***.***> ha scritto:
