### ISSUE TITLE
cloupe file to Loupe Brower8.0 get a different plot

### ISSUE THREAD

**Issue by jiangldu** [10XGenomics/loupeR#55]
hello,
when  importing cloupe file to Loupe Brower8.0 , i got a different plot comparing with dimplot(). In Loupe Brower, when seting "split view", it would get a very scattered plot. 
use FindIntegrationAnchors() and IntegrateData() functions to merge 10xgenomic datasets. 
use create_loupe() to get cloupe file , the commands as. 
create_loupe(count_mat = GSE165318.combined@assays$RNA$counts,
             clusters = clusters,
             projections = projections,
             output_dir = "./",
             output_name = "GSE165318.combined.1",
             seurat_obj_version = "Seurat4")
DimPlot(GSE165318.combined,reduction = "tsne",group.by = "seurat_clusters")
DimPlot(GSE165318.combined,reduction = "tsne",group.by = "seurat_clusters",
        split.by = "celltype")

> ls(projections)
[1] "tsne" "umap"
> ls(clusters)
[1] "active_cluster"         "celltype"               "GSE.Group"             
[4] "GSE.Sample"             "integrated_snn_res.0.5" "orig.ident"            
[7] "Row.names"              "seurat_clusters" 

plots in Loupe Brower:
<img width="820" alt="image" src="https://github.com/10XGenomics/loupeR/assets/42030436/24c5d8c9-653f-481f-b8c2-b8ded26aa1c3">
<img width="588" alt="image" src="https://github.com/10XGenomics/loupeR/assets/42030436/f038689d-db88-4278-92d3-3a84ddcf2c85">

**Comment by gmjoseph** [comment]
hi @jiangldu thanks for filling this issue - could you also share the result of `dimplot()` please? thank you.

**Comment by jiangldu** [comment]
dimplot :
![image](https://github.com/10XGenomics/loupeR/assets/42030436/e2405f6d-daec-4196-b7dd-66f5dc3ffb30)

**Comment by esiegel** [comment]
@jiangldu It's hard to know what's going on from images.  Would you be able to share an RDS export of the seurat object before you export it as a Loupe file.

I'm not a scientist, so it might be best to reach out to support@10xgenomics.com

**Comment by jiangldu** [comment]
sorry, i forgot to reply.  I has solve it. when using create_loupe function, the locatins(x/y )  were disordered.
