### ISSUE TITLE
ERROR:make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version):    invalid non-character version specification 'x' (type: double)

### ISSUE THREAD

**Issue by FourAlarmFire** [10XGenomics/loupeR#57]
I am trying use 
`create_loupe_from_seurat(
    sce.sub ,
    output_dir = pa_pathway,
    output_name = pa_celltype,
    dedup_clusters = FALSE,
    executable_path = NULL,
    force = T
  )
  `
but i was encountered the error

> 2024/07/03 14:57:31 extracting matrix, clusters, and projections
error:.make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version): 
  invalid non-character version specification 'x' (type: double)

I donnot konw how to solve, and if it is my seurat object that has some problems,
hope you can reslove, thanks!

**Comment by gmjoseph** [comment]
Hi @FourAlarmFire thanks for writing in - looks like you're running into the same issue as this user: https://github.com/10XGenomics/loupeR/issues/52

Please try upgrading to the latest version of loupeR (1.1.1) and I believe that should fix the problem. If not, please file another issue.
