### ISSUE TITLE
no slot of name "counts" for this object of class "Assay5" error message

### ISSUE THREAD

**Issue by BartBryant** [10XGenomics/loupeR#58]
thanks for developing loupeR, has worked great for all my Seurat objects to help share data to others

however, i have a seurat object where our collaborator removed doublets with 'singleCellTK'; however, now i get the error message 
#Error in select_assay(obj) : 
#  no slot of name "counts" for this object of class "Assay5"
after running 'create_loupe_from_seurat(  )' function from 'loupeR'.

seems 'singleCellTK' to filter doublets altered the structure of my SeuratObject, 
so what is the structure a SeuratObject needs to be in order to run loupeR?

thanks and let me know if you need more info

**Comment by esiegel** [comment]
By default loupeR looks for the counts matrix at `assay$counts`.  It seems that the `singleCellITK` tool creates a new counts matrix at `decontXcounts` as can be seen [here](https://github.com/compbiomed/singleCellTK/blob/578583f9f09189c0196288ca046e9bd4e31567be/R/seuratFunctions.R#L1682-L1683).

The error message should probably be updated and it should fail more gracefully.

For now you can get around this issue by directly calling `create_loupe` and passing in the appropriate parameters.

**Comment by esiegel** [comment]
Closing as there is a work around.
