### ISSUE TITLE
Include more metadata

### ISSUE THREAD

**Issue by deepalivasoya** [10XGenomics/loupeR#6]
Hello! I appreciate your helpful package. I was waiting for it. I've given it a try, and it's been successful. I have a query regarding the process of adding metadata from the Seurat object to a Loupe file. I've observed that not all metadata is included in the Loupe file, but some are. Is there a specific criterion for pre-selecting which metadata to include? Thank you.

**Comment by esiegel** [comment]
When you say `metadata` are you referring to the the data that can be accessed via `seurat_obj@meta.data` (here `seurat_obj` is some `SeuratObject`)?  Or is there some other data that you are hoping would be included, but is not?

Currently, this tool selects the clusters by iterating over every column in the `meta.data` dataframe and retaining those that are either a `factor` or a character vector which we convert to a factor.  The logic can be seen [here](https://github.com/10XGenomics/loupeR/blob/942265909f592f4e61cdcda7ec70b430c5bc4ba0/R/util.R#L80-L96).

**Comment by deepalivasoya** [comment]
Yes I mean seurat_obj@meta.data. Thank you for your quick reply. I can see now why only certain columns were retained and others weren't. It was helpful to know how they were selected. I can convert some metadata into factor to include in loupe file. 

Cheers!

**Comment by deepalivasoya** [comment]
Skipping numeric columns does seem reasonable. In my dataset, I've added numerous columns through custom quality control and cell selection processes. By default, LoupeR selects some of these columns based on their character class and factors. However, I don't want all of them to be included, so I plan to create a new object that contains the metadata I specifically want to include in Loupe. Additionally, I'd like to include extra logical columns that can aid in visualizing or selecting cells as either true or false. I guess creating new object that has only those metadata I want in loupe (which is around 7 columns) should work. Thanks

**Comment by esiegel** [comment]
No need to create a new Seurat object, but you can if that is easiest.  I would recommend using the function `create_loupe` directly and passing the clusters that you want.  Something like this:

```R
# import the library
library("loupeR")

# Gene Expression RNA assay
assay <- seurat_obj[["RNA"]]

# select some of the clusters and add some more.
all_clusters <- select_clusters(seurat_obj)
clusters <- list(A = all_clusters[["clusterA"]], B = all_clusters[["clusterB"]])
clusters[["extra"]] = factor(seq(1000))

# convert the count matrix, clusters, and projections into a Loupe file
create_loupe(
    assay@counts,
    clusters = clusters,
    projections = select_projections(seurat_obj)
)
```
