### ISSUE TITLE
Can not recognize the scATAC-seq .cloupe file in Loupe Browser

### ISSUE THREAD

**Issue by xychen24** [10XGenomics/loupeR#62]
Hi, i created a loupe file from my seurat object(scATAC-seq), like this:
`DefaultAssay(seu) <- "peaks"`
`head(rownames(seu@assays$peaks)) #'chr1:190970-191891''chr1:267555-268452''chr1:585752-586646''chr1:629498-630393''chr1:633578-634475''chr1:778297-779209'  `
`create_loupe_from_seurat(seu)  `

However, when i open this cloupe file in Loupe Browser, the interface indicates that this is a single-cell RNA sequencing (scRNA-seq) file, which means there are no accessibility choice but expression choice. Is there something wrong when i create the loupe file?
Thanks for your attention :）
![image](https://github.com/user-attachments/assets/77f9a32b-cc1c-4038-8410-629a4b28357e)

**Comment by gmjoseph** [comment]
Hi @xychen24 thanks for raising this issue.

At the moment we only support single-cell gene expression datasets. There is a chance we may add ATAC support in future, so please watch out for that if/when we do.
