### ISSUE TITLE
Feature linkage with ChromatinAssay

### ISSUE THREAD

**Issue by ChristopherBarrington** [10XGenomics/loupeR#64]
Is it possible to include a Feature Linkage output from a Seurat (+Signac) object? I have a Seurat object with a ChromatinAssay assay from Signac. When I export the object as a Loupe file I get the expected expression data but would be nice to have the feature linkage information too - particularly after Cell Ranger ARC peaks are redefined following filtering.

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/16e8faf9-8efe-4a13-9955-0d56fd219be6">

**Comment by dylanwebster** [comment]
Hi Chris, unfortunately LoupeR does not support ATAC data or the ATAC portion of multiome datasets. We will make note of your interest to consider adding this in the future. In general, we also welcome PRs from the community to improve LoupeR!
