### ISSUE TITLE
Spatial projection not present

### ISSUE THREAD

**Issue by 532at** [10XGenomics/loupeR#66]
Hello,

I do not see a spatial projection when generating loupeR file from my Seurat object from Visium experiment. There is only UMAP and FeaturePlot projections.

Could you help me with that? How to include Spatial projection in the export loupeR file?

Thank you,
Adrian

**Comment by megannguyen1009** [comment]
I am having the same issue with my dataset. My seurat object has 80 images, but generating a .cloupe file and loading into the Loupe Browser only shows the UMAP and feature plot projections. Has anyone figured out how to load the spatial projections? I would like to be able to see my images on the Loupe Browser

**Comment by esiegel** [comment]
Currently, importing images and other spatial data is not supported in loupeR.  it is definitely something on the roadmap, but will take some work.

I am interested to learn more about your process and about the images.  Are the images very large and would need tiling?  What format are they?

**Comment by megannguyen1009** [comment]
so the only spatial data we are able to navigate through are the public datasets at the moment?

**Comment by megannguyen1009** [comment]
the Loupe Browser information given from the 10x Genomics site makes it sound like we can load in our own spatial data

**Comment by esiegel** [comment]
The Loupe Browser can load public spatial datasets and also any private spatial dataset that is created via [spaceranger](https://www.10xgenomics.com/support/software/space-ranger/latest).  LoupeR support to import data other then cell expression data hasn't been implemented.

**Comment by esiegel** [comment]
Closing for now as the question has been answered.  Please feel free to reopen if there is something else
