### ISSUE TITLE
How to get expression matrix from cloupe file in R or Loupe browser?

### ISSUE THREAD

**Issue by bigbrolv** [10XGenomics/loupeR#7]
I get a few cloupe(Visium) files from research paper, but i can only get coordinate data from Loupe browser.

**Comment by bigbrolv** [comment]
How to get expression matrix from cloupe file in R or Loupe browser?

**Comment by esiegel** [comment]
Currently it is not possible to extract the expression matrix from a cloupe file.  Definitely something interesting that I think we could consider.  If the paper links to the rest of the cellranger outputs then you could import the expression matrix from that data.  For now I'll pass this request along to some folks at 10x.

**Comment by tfguinan** [comment]
I had this same question and found the cloupe python module that will build an anndata object from the cloupe file: https://github.com/cellgeni/cloupe
