### ISSUE TITLE
Issues running multi-sample differential expression

### ISSUE THREAD

**Issue by CoolandHot** [10XGenomics/loupeR#72]
Hi there, thank you for developing this amazing tool. I use Seurat in R to work on a Visium HD project. I would like to ask some question about it and suggest a possible upgrade. 

Although it's not feasible to directly export Visium V2 object from Seurat to CLOUPE `create_loupe_from_seurat`, I'm able to work around with 
```
create_loupe(
    count_mat,
    clusters = list(),
    projections = list(),
    output_dir = NULL,
    output_name = NULL,
    feature_ids = NULL,
    executable_path = NULL,
    force = FALSE,
    seurat_obj_version = NULL
    )
```

The only limitation is that I want to export the **tissue image** as the spatial background (auto-aligned if possible) and the **differential gene expression** results as well.

I exported the two clusters, one is SNN-base cluster on the gene expression, another is simply the sample conditions. It goes into error when I try to run the **Across multiple samples** differential expression analysis in the Loupe Browser (ver 8.0.0) by selecting the SNN-base clusters as the cell type group, experimental conditions as the condition group. 
![image](https://github.com/user-attachments/assets/ff8fa656-9935-475c-a3a1-d42082f78e0d)
Is there an example document I can follow and format my data into?

I hope there will be more documents in exporting/editing *.cloupe format other than the one and only https://www.10xgenomics.com/support/software/loupe-browser/latest/tutorials/introduction/lb-louper . 

Thank you in advance.

**Comment by esiegel** [comment]
It might be best to reach out to support@10xgenomics.com for help with the multi-sample differential expression.  Looking at the screen shot, you probably need to update your cluster to be called `SampleID`.  

I assume that normal differential expression is still working.  Importing images is something that we get requested more and more and are discussing.

**Comment by CoolandHot** [comment]
> It might be best to reach out to [support@10xgenomics.com](mailto:support@10xgenomics.com) for help with the multi-sample differential expression. Looking at the screen shot, you probably need to update your cluster to be called `SampleID`.
> 
> I assume that normal differential expression is still working. Importing images is something that we get requested more and more and are discussing.

Hi Esiegel, thank you so much! I would love to see the updated package soon! :)

**Comment by esiegel** [comment]
Closing with the assumption that changing the clusters to be called `SampleID` will solve the problem.  Please reopen if you continue to have issues.
