### ISSUE TITLE
Issue when using `create_loupe_from_seurat`

### ISSUE THREAD

**Issue by thecatsmilk** [10XGenomics/loupeR#74]
Hello! Thanks for making such a great tool, really helps with sharing analyzed data with biologists! I have a quick question regarding `clusters`. I have a Seurat object (`timecourse`) with 33,678 cells. When running the following:

```
timecourse_loupe <- create_loupe_from_seurat(timecourse)
```

I receive the following error:

```
2024/11/13 14:39:41 extracting matrix, clusters, and projections
2024/11/13 14:39:48 selected assay: RNA
2024/11/13 14:39:48 selected clusters: active_cluster orig.ident X predicted_doublet Sample_name cellLine culture_set Seeding StageDay anchor format OG_name molec_added edit iPS_expansion_matrix iPS_expansion_medium diff_matrix ingest_ct phase cellType final_cellType CHGA_pos
2024/11/13 14:39:48 selected projections: umap
2024/11/13 14:39:48 validating count matrix
2024/11/13 14:39:52 validating clusters
Error in create_loupe(counts, clusters = clusters, projections = projections,  : 
  
It looks like the formatting of your clusters does not match the required formatting for LoupeR. For further information, please see the documentation: 10xgen.com/louper

cluster cannot have more than 32768 groupings
```

I immediately thought that I had too many cells than what is currently supported, so, I just randomly sampled 30,000 cells from `timecourse` and re-ran the conversion function:

```
# too many cells, need to cut down (limited to ~32,000 cells)
timecourse_subsampled <- timecourse[, sample(colnames(timecourse), size = 30000, replace = F)]
timecourse_loupe <- create_loupe_from_seurat(timecourse_subsampled)
```

And it ran with no issues and loaded flawlessly in the Loupe browser.

I am curious as to what `clusters` are, as I saw in the code that they are a list of factors that hold information for each barcode. Is this information the metadata columns and features associated with each barcode? Any information would be greatly appreciated. Thank you!

Dan

**Comment by esiegel** [comment]
> I am curious as to what `clusters` are, as I saw in the code that they are a list of factors that hold information for each barcode. Is this information the metadata columns and features associated with each barcode?

Yes, the clusters, by default, are pulled from the metadata columns.  You can see the logic [here](https://github.com/10XGenomics/loupeR/blob/a169417e7a0d59ae7ebba042a4f100de8efb8101/R/util.R#L100-L126).  If you instead used the `create_loupe` function you could pass in any custom clusters that you wanted.  As long as they pass [validation](https://github.com/10XGenomics/loupeR/blob/a169417e7a0d59ae7ebba042a4f100de8efb8101/R/validate.R#L126-L161).

Going back to your specific problem, I assume that one of the factors in the metadata has a unique value for each of the 33,678 cells.  Loupe has a hard limit on the number of subgroups that can be within any one grouping and each of these metadata factors will eventually become a grouping.

I think your best option is to modify the code in `create_loupe_from_seurat` something like this:

```r
namedAssay <- select_assay(timecourse)
assay_name <- names(namedAssay)
assay <- namedAssay[[1]]
counts <- counts_matrix_from_assay(assay)

clusters <- select_clusters(timecourse, dedup=FALSE)
projections <- select_projections(timecourse)

# remove clusters with too many levels
is_valid <- function(cluster) {
  n <- nlevels(cluster)
  return(n > 0 && n <= 32768)
}
clusters <- Filter(is_valid, clusters)

create_loupe(
  counts,
  clusters=clusters,
  projections=projections,
  seurat_obj_version=as.character(timecourse@version),
)
```

**Comment by thecatsmilk** [comment]
Awesome, this clarifies it. Thank you so much!
