### ISSUE TITLE
create_loupe_from_seurat() error: Barcodes should begin with base pairs and end with an optional hyphen and suffix

### ISSUE THREAD

**Issue by m-fayer** [10XGenomics/loupeR#8]
Hi,

I tried to convert 10x formatted matrix files (barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz; example files are [here](https://bgitech-my.sharepoint.com/:u:/g/personal/likaimao_genomics_cn/EQCicmvD0KpEvbath8aa-WgB9Anqbnf7dIiWqhy9Xght2Q?e=xlbulP)) into cloupe file. The code I used is as below.

```
library(Seurat)
library(loupeR)
sp6_data <- Read10X(data.dir = "/path/to/above/example/files", gene.column = 1)
pbmc=CreateSeuratObject(counts = sp6_data, min.cells = 3, min.features = 200)
pbmc <- ScaleData(pbmc, verbose = FALSE)
pbmc <- FindVariableFeatures(object = pbmc)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- RunUMAP(pbmc, dims = 1:10)
pbmc <- FindNeighbors(pbmc, dims = 1:30)
pbmc <- FindClusters(pbmc, resolution = 0.8)
loupe_sp6<-create_loupe_from_seurat(pbmc,output_name="loupe_sp6_from_seurat")
```

The last step showed an error:
<pre>
2023/10/05 02:13:22 extracting matrix, clusters, and projctions
2023/10/05 02:13:22 selected assay: RNA
2023/10/05 02:13:22 selected clusters: active_cluster orig.ident RNA_snn_res.0.8 seurat_clusters
2023/10/05 02:13:22 selected projections: umap
2023/10/05 02:13:22 validating count matrix
2023/10/05 02:13:22 validating clusters
2023/10/05 02:13:22 validating projections
2023/10/05 02:13:24 validating input file: /tmp/Rtmp59LgRw/file11a41805552.h5
2023/10/05 02:13:26 Dataset "/matrix/barcodes": There is an issue with the formatting of your barcodes.  
<b>Barcodes should begin with base pairs and end with an optional hyphen and suffix.</b>
For further information, please see the documentation: 10xgen.com/louper
Error in create_loupe(assay@counts, clusters = clusters, projections = projections,  : 
  
It looks like there was an issue with creating the loupe file. For further information, please see the documentation: 10xgen.com/louper

Louper executable failed: status code 1
</pre>

My barcodes were formatted with something like "AAACCCAAGGCATCAG-1", complying with "Barcodes should begin with base pairs and end with an optional hyphen and suffix". Why this error? Thanks in advance.

**Comment by esiegel** [comment]
I know the data is formatted in the 10x layout, but does the data originate from a 10x experiment? The `loupeR` tool only supports conversion of 10x data.  Technically, converting non 10x data is a violation of our [End User License Agreement](https://www.10xgenomics.com/legal/end-user-software-license-agreement)

Please let me know if this is not the case and I can investigate further.

**Comment by esiegel** [comment]
Also, you can run `loupeR::create_bugreport_from_seurat(pbmc)` to output a summary that can be pasted here in Github or sent to support.

**Comment by liangyuli12138** [comment]
Hi, I have met the same problem. I try to Rename cell names but not work, could you tell me how to fix it ?
#=============
This is my `create_bugreport_from_seurat()` result:
```R

Metadata:

tool: loupeR
tool_version: 1.0.1
os: CentOS Linux 7 (Core)
system: x86_64-pc-linux-gnu (64-bit)
language: R
language_version: 4.2.1
extra:
     loupeR_seurat_version: 4.3.0
     loupeR_seurat_object_version: 5.0.1
     loupeR_hdf5r_version: 1.3.6
     loupeR_hdf5_version: 1.10.7

Selections:

selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    CellType_Category
    Manuscript_Identity
    Subclass_Cell_Identity
    Disease_Identity
    Subject_Identity
    Library_Identity
selected projections:
    umap

Matrix Sampling:

feature count: 42628
barcode count: 243472
feature sampling:
    RBM14
    MARK1
    LINC00857
    ENSG00000259536
    ENSG00000241183
    WDR24
    HOTTIP
    TRMT12
    ENSG00000273138
    LINC00476
barcode sampling:
    TCACAAGGTATGAATG-051I_a
    CTTCTCTTCAGTGCAT-051I
    CGGAGCTGTTACAGAA-59I
    CGCTGGACATAAGACA-92C
    TTATGCTCAGCAGTTT-158I_b
    GCTTGAAAGCTAACTC-133C_a
    GCATGATTCTAGAGTC-209I_a
    CTACACGACGCTCTTC-040I_b
    GTAACGTCAAGTTGTC-208C
    AGATTGCGTTCCGGCA-145I_a

Validation:

    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
```
Thanks a lot
