### ISSUE TITLE
How can I covert the .cloupe file into the format Seurat can read?

### ISSUE THREAD

**Issue by Biomamba** [10XGenomics/loupeR#9]
Dear author:
    How can I covert the .cloupe file into the format Seurat can read?

**Comment by esiegel** [comment]
This tool does not currently support taking a `cloupe` file and converting it into a Seurat file.  It only allows the other direction.  You are not the first to ask for this feature and it is definitely something on our radar.

**Comment by esiegel** [comment]
Closing, but feel free to reopen if I haven't addressed your issue.

**Comment by dylanwebster** [comment]
Hi @Biomamba I'm from the software product team at 10x Genomics and I'd be interested in talking with you to learn more about your Loupe and LoupeR usage, and how converting from .cloupe to Seurat could accelerate your analysis. If you're interested in discussing this, you can reach out at dylan.webster@10xgenomics.com. Hope to hear from you!
